language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml2-utils
services:
  - docker      
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
          
install:
  - export PATH="/usr/local/bin:$PATH"
  - npm config set unsafe-perm true
  - npm install bower gulp -g
  # Downgrades Node.js, due to lib clash (https://github.com/Rothamsted/knetminer/issues/432)
  # TODO: remove after the mentioned issue is fixed.
  - npm install -g n
  - npath=$(which n) # we need this, cause the installation is somewhere in $HOME and 'n' needs sudo
  - sudo $npath 11.15.0 
      
script:
  # Avoids timeouts due to our Nexus instability
  - travis_wait 30 ./travis-build.sh
  
branches:
  only:
  - master
  - 201912_saveNetworks
