language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml2-utils
services:
  - docker      
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
          
install:
  - npm config set unsafe-perm true
  - npm install bower gulp -g
  - export PATH="/usr/local/bin:$PATH"
      
script: 
  - ./travis-build.sh