language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml2-utils
services:
  - docker      
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
          
install:
  - export PATH="/usr/local/bin:$PATH"
  - npm config set unsafe-perm true
  - npm install bower gulp -g
  - npm install -g n
  - which n
  - sudo /usr/local/bin/n 11.15.0 # TODO: Remove after fix of https://github.com/Rothamsted/knetminer/issues/432
      
script: 
  - ./travis-build.sh