language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml2-utils
services:
  - docker      
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
          
install:
  - npm config set unsafe-perm true
  - npm install bower gulp -g
  - export PATH="/usr/local/bin:$PATH"
      
script: 
  # You need --quiet, Travis doesn't like too big logs.
  - mvn --quiet deploy --settings settings.xml
  - echo -e "\n\n\tDocker-base"
  - docker build --no-cache -t knetminer/knetminer-base -f common/quickstart/Dockerfile-base .
  - echo -e "\n\n\tDocker"
  - docker build --no-cache -t knetminer/knetminer -f common/quickstart/Dockerfile .
  - echo -e "\n\n\tPushing Docker-base"
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PWD"
  - docker push knetminer/knetminer-base 
  - echo -e "\n\n\tPushing Docker"
  - docker push knetminer/knetminer
 
  