language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - libxml2-utils
      
before_script:
  - npm config set unsafe-perm true
  - npm install bower gulp -g
      
script: 
  - mvn deploy --settings settings.xml
