name: Docker Test

on:
  workflow_dispatch
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2.3.4
    
    # This is to test ARM, comment it and leave "run" if you don't need to specify the architecture. 
    - uses: uraimo/run-on-arch-action@v2.0.9
      name: Run aratiny
      id: docker-cmd
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          cd docker
          ./docker-run.sh
